name: Delete Older Releases

on:
  workflow_dispatch:

jobs:
  delete-older-releases:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
